Resources:
  EC2Test:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0528a5175983e7f28
      InstanceType: t2.micro
      KeyName: cca-linux-key-pair
      SecurityGroups:
        - !Ref EC2TestSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sdh
          Ebs:
            VolumeType: io1
            Iops: '40'
            DeleteOnTermination: 'false'
            VolumeSize: '1'
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - |
              mkdir /mnt/xvdh
            - |
              mkfs -t ext4 /dev/xvdh
            - |
              echo "/dev/xvdh /mnt/xvdh ext4 defaults,nofail 0 2" >> /etc/fstab
            - |
              mount -a
    DependsOn:
      - EC2TestSecurityGroup
  EC2TestSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow SSH into EC2Tester
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
Outputs:
  Description: EBS Volume ID 
  Value: !Ref Ebs